name: basic_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg_provider: ^1.0.3
  http: ^0.13.5
  hexcolor: ^3.0.1
  flutter_native_splash: ^2.2.18
  shared_preferences: ^2.0.17
  form_field_validator: ^1.1.0
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
